import type { Metadata } from 'next';
import './globals.css';

import ScrollProgress from '@/components/ScrollProgress';
import TopLoader from '@/components/TopLoader';
import { ToastProvider } from '@/components/ToastProvider';
import BackgroundFX from '@/components/BackgroundFX';
import CursorGlow from '@/components/Cursor';
import Splash from '@/components/Splash';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body>
                <TopLoader />
                <BackgroundFX />
                <CursorGlow />
                <ToastProvider>
                    <Splash />
                    <ScrollProgress />
                    {children}
                </ToastProvider>
            </body>
        </html>
    );
}
