import type { Metadata } from 'next';
import './globals.css';

import ScrollProgress from '@/components/ScrollProgress';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body>
                <ScrollProgress />
                {children}
            </body>
        </html>
    );
}
